# Site settings
title: nemui
description: > # this means to ignore newlines until "baseurl:"
  nemui
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nemui.github.io" # the base hostname & protocol for your site
github_username:  nemui

# Build settings
markdown: kramdown
highlighter: true
